# Generated by Django 5.2.4 on 2025-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_author_date_born_alter_author_date_death'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='bookproduct',
            old_name='genre',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
