# Generated by Django 5.2.4 on 2025-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_genre_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='language',
            field=models.CharField(choices=[('UKR', 'Українська'), ('ENG', 'Англійська')], default='UKR', max_length=3),
        ),
    ]
