# Generated by Django 5.2.4 on 2025-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_bookproduct_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='pictures',
            field=models.CharField(choices=[('COL', 'Кольорові'), ('BW', 'Чорно-білі'), ('NON', 'Відсутні')], default='NON', max_length=3),
        ),
    ]
