# Generated by Django 5.2.4 on 2025-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_bookproduct_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='photo',
            field=models.FileField(null=True, upload_to='img'),
        ),
    ]
