# Generated by Django 5.2.4 on 2025-07-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_bookproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
